from Pessoajuridica import Pessoajuridica

pessoa1=Pessoajuridica(7,30,40.000,"pix",100.000,"15/11/24","09/11/24","13:36hrs",["moto","moto"],["www.anuncio2.com.br","www.anuncio3.com.br"],"20/11/24","15/02/25","Mercedez","00.623.904/0001-73","José de Alencar")
pessoa2=Pessoajuridica(8,16,40.000,"empréstimo",100.000,"15/11/24","09/11/24","14:30hrs",["moto","carro"],["www.anuncio3.com.br","www.anuncio7.com.br"],"21/11/24","15/03/25","BMW","00.624.905/0001-74","Maria Antonieta")


print("Identificador"+ str (pessoa1. getId()))
print("Identificador do vendedor:"+ str (pessoa1.getIdvende()))
print("Preço a pagar:"+str (pessoa1.getPrecopagar()))
print("Forma de pagamento"+pessoa1.getPagamento())
print("Total da venda:"+ str (pessoa1.getTotalvenda()))
print("Data de entrega:"+pessoa1.getDataentrega())
print("Data de inicio da compra:"+pessoa1.getDatainicio())
print("Hora da compra:"+pessoa1.getHora())
print("Veículos comprados:"+str (pessoa1.getListacomprado()))
print("Data de reserva:"+pessoa1.getDatareserva())
print("Prazo de reserva:"+pessoa1.getPrazoreserva())
print("Nome da empresa:"+pessoa1.getNomeempresa())
print("Cnpj do cliente"+pessoa1.getCnpjcliente())
print("Nome do responsavel:"+pessoa1.getNomerespon())
print("")
print("Identificador"+ str (pessoa2. getId()))
print("Identificador do vendedor:"+ str (pessoa2.getIdvende()))
print("Preço a pagar:"+str (pessoa2.getPrecopagar()))
print("Forma de pagamento"+pessoa2.getPagamento())
print("Total da venda:"+ str (pessoa2.getTotalvenda()))
print("Data de entrega:"+pessoa2.getDataentrega())
print("Data de inicio da compra:"+pessoa2.getDatainicio())
print("Hora da compra:"+pessoa2.getHora())
print("Veículos comprados:"+str (pessoa2.getListacomprado()))
print("Data de reserva:"+pessoa2.getDatareserva())
print("Prazo de reserva:"+pessoa2.getPrazoreserva())
print("Nome da empresa:"+pessoa2.getNomeempresa())
print("Cnpj do cliente"+pessoa2.getCnpjcliente())
print("Nome do responsavel:"+pessoa2.getNomerespon())
