from Pessoafisica import Pessoafisica

pessoa1=Pessoafisica(3,10,800.000,"débito",90.0000,"25/12/2024","08/11/24","17:30hrs",["caminhão","carro"],['www.anuncio1.com.br'],"20/12/23","24/12/24","Roberto","123456789","True")
pessoa2=Pessoafisica(4,11,800.000,"financiamento",100.0000,"28/12/2024","08/01/25","17:30hrs",["caminhão","carro"],['www.anuncio2.com.br'],"20/12/23","24/12/24","Rayssa","2222323233233","True")

print("Identificador"+ str (pessoa1. getId()))
print("Identificador do vendedor:"+ str (pessoa1.getIdvende()))
print("Preço a pagar:"+str (pessoa1.getPrecopagar()))
print("Forma de pagamento"+pessoa1.getPagamento())
print("Total da venda:"+ str (pessoa1.getTotalvenda()))
print("Data de entrega:"+pessoa1.getDataentrega())
print("Data de inicio da compra:"+pessoa1.getDatainicio())
print("Hora da compra:"+pessoa1.getHora())
print("Veículos comprados:"+str (pessoa1.getListacomprado()))
print("Data de reserva:"+pessoa1.getDatareserva())
print("Prazo de reserva:"+pessoa1.getPrazoreserva())
print("Nome do cliente:"+pessoa1.getNomecliente())
print("CPF do cliente:"+pessoa1.getCpfcliente())
print("Confirmamento da venda:"+pessoa1.getVendacon())
print("")
print("Identificador"+ str (pessoa2. getId()))
print("Identificador do vendedor:"+ str (pessoa2.getIdvende()))
print("Preço a pagar:"+str (pessoa2.getPrecopagar()))
print("Forma de pagamento"+pessoa2.getPagamento())
print("Total da venda:"+ str (pessoa2.getTotalvenda()))
print("Data de entrega:"+pessoa2.getDataentrega())
print("Data de inicio da compra:"+pessoa2.getDatainicio())
print("Hora da compra:"+pessoa2.getHora())
print("Veículos comprados:"+str (pessoa2.getListacomprado()))
print("Data de reserva:"+pessoa2.getDatareserva())
print("Prazo de reserva:"+pessoa2.getPrazoreserva())
print("Nome do cliente:"+pessoa2.getNomecliente())
print("CPF do cliente:"+pessoa2.getCpfcliente())
print("Confirmamento da venda:"+pessoa2.getVendacon())
